### ISSUE TITLE
Model Extension

### ISSUE THREAD

**Issue by hanwenzhang0317** [hanwenzhang0317/MXCS-SVAR#3]
Hi @donotdespair ,

I am interested in including heteroskedastic error terms as an extension since I am including stock prices as one of the variables in the SVAR model, for which the time series is not linear and volatility is not constant over time.  

Would you recommend it is plausible? 

Bests,
Hanwen

**Comment by donotdespair** [comment]
Hi @hanwenzhang0317 

Each of you will be doing the heteroskedasticity part. So, the extension of your model proposed now has to be different. Heteroskedasticity is plausible for every model you are using. So, that's good news :)

Would you please propose another extension here? Thanks! And remember to tag me every time you await my response :)

**Comment by hanwenzhang0317** [comment]
Hi @donotdespair , 

Thanks for the clarification, I would like to work on hyper-parameters as my extension of the model, $\kappa_1$ and $\kappa_2$. 

As the Minnesota prior reflects,

$$\begin{eqnarray} 
p(A|\Sigma) = p(A|\Sigma) \times p(\Sigma)  
\end{eqnarray}$$

$$\begin{eqnarray} 
A|\Sigma \sim MN_{K \times N}(\underline{A},\Sigma,\underline{V})
\end{eqnarray}$$

$$\begin{eqnarray} 
\Sigma \sim IW_{N}(\underline{s},\underline{\nu})
\end{eqnarray}$$

where,

$$
vec(A) \sim N_{KN}(vec(\underline{A}),\Sigma \otimes \underline{V})
$$

$$
\underline{V} = diag([\kappa_2 \quad \kappa_1(p^{-2} \otimes I_{n}^{'})])
$$

Now as an extension, we can specify $\kappa_1$ and $\kappa_2$ follows a certain distribution rather than being set as a constant, e.g. 

$$
\kappa \sim IG2(s_{\kappa}, \nu_{\kappa})
$$

then we might have 

$$
\Sigma | \kappa \sim IW_{N}(\underline{s}_{\kappa},\underline{\nu} _{\kappa})
$$

Does it work like this? Any clarification will be greatly appreciated!

**Comment by hanwenzhang0317** [comment]
Hi @donotdespair,

I just checked notes and found something there. 

$$
A | \Sigma, \kappa \sim MN_{K \times N} (\underline{A}, \Sigma, \kappa \underline{V} ) 
$$

$$
\Sigma \sim IW_{N} (\underline{s}, \underline{\nu})
$$

$$
\kappa \sim IG2_{N} ( \underline{s} _ {\kappa} , \underline{\nu} _ {\kappa})
$$

Then the variance of $vec(A)$ becomes $\Sigma \otimes \kappa \underline{V} = \kappa (\Sigma \otimes \underline{V})$

Then we have the full conditional posterior becomes,

$$
p(A| \Sigma , \kappa) \times p(\Sigma) \times p(\kappa)
$$

And we can draw $p(A,\Sigma | Y, X, \kappa) \sim MNIW_{K \times N}(\bar{A}, \kappa \bar{V}, \bar{s}, \bar{\nu})$ and $p(\kappa | A, \Sigma, Y, X) \sim IG2 (\bar{s_{\kappa}}, \bar{\nu _{\kappa}}) $.

**Comment by donotdespair** [comment]
> Hi @donotdespair,
> 
> I just checked notes and found something there.
> 
> A|Σ,κ∼MNK×N(A―,Σ,κV―)
> 
> Σ∼IWN(s―,ν―)
> 
> κ∼IG2N(s―κ,ν―κ)
> 
> Then the variance of vec(A) becomes Σ⊗κV―=κ(Σ⊗V―)
> 
> Then we have the full conditional posterior becomes,
> 
> p(A|Σ,κ)×p(Σ)×p(κ)
> 
> And we can draw p(A,Σ|Y,X,κ)∼MNIWK×N(A¯,κV¯,s¯,ν¯) and p(κ|A,Σ,Y,X)∼IG2(sκ¯,νκ¯).

Hi @hanwenzhang0317 

The prior setup in the post above is all correct. Nice!

The posterior derivations are not. Just derive the column-specific posterior covariance of `A` again to get the details right!

**Comment by hanwenzhang0317** [comment]
Hi @donotdespair ,

When independently drawing $\kappa$ from, 

$$
\kappa \sim IG2 ( \underline{s} _ {\kappa}, \underline{\nu} _ {\kappa} )
$$

Should $\underline{s} _ {\kappa}$ and $\underline{\nu} _ {\kappa}$ be assumed to be some value? Or is there any way to identity what is a proper value for them?

**Comment by donotdespair** [comment]
Hi @hanwenzhang0317 

Yes, indeed, you need to fix them to specific numbers. Please motivate your choices in the empirical example when it comes to that. Think of the prior means and variances implied by these values.

**Comment by hanwenzhang0317** [comment]
The issue is closed
